src/gz immortalwrt_core https://mirrors.ustc.edu.cn/immortalwrt/releases/23.05.4/targets/armsr/armv8/packages
src/gz immortalwrt_base https://mirrors.ustc.edu.cn/immortalwrt/releases/23.05.4/packages/aarch64_generic/base
src/gz immortalwrt_luci https://mirrors.ustc.edu.cn/immortalwrt/releases/23.05.4/packages/aarch64_generic/luci
src/gz immortalwrt_packages https://mirrors.ustc.edu.cn/immortalwrt/releases/23.05.4/packages/aarch64_generic/packages
src/gz immortalwrt_routing https://mirrors.ustc.edu.cn/immortalwrt/releases/23.05.4/packages/aarch64_generic/routing
src/gz immortalwrt_telephony https://mirrors.ustc.edu.cn/immortalwrt/releases/23.05.4/packages/aarch64_generic/telephony

